name: Portfolio Update

on:
  schedule:
    # Runs at the top of every hour
    - cron: "0 * * * *"

jobs:
  update_portfolio:
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ vars.NOTION_TOKEN }}
      NOTION_TRADES_DATABASE_ID: ${{ vars.NOTION_TRADES_DATABASE_ID }}
      NOTION_BALANCES_DATABASE_ID: ${{ vars.NOTION_BALANCES_DATABASE_ID }}
      NOTION_PORTFOLIO_VALUE_DATABASE_ID: ${{ vars.NOTION_PORTFOLIO_VALUE_DATABASE_ID }}
      KRAKEN_API_KEY: ${{ vars.KRAKEN_API_KEY }}
      KRAKEN_API_SECRET: ${{ vars.KRAKEN_API_SECRET }}
      BINANCE_API_KEY: ${{ vars.BINANCE_API_KEY }}
      BINANCE_API_SECRET: ${{ vars.BINANCE_API_SECRET }}
      BYBIT_API_KEY: ${{ vars.BYBIT_API_KEY }}
      BYBIT_API_SECRET: ${{ vars.BYBIT_API_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "19" # Set this to the node version you need
          cache: "yarn"

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Compile TypeScript
        run: yarn build

      - name: Run the script
        run: node dist/balances.js # Adjust the path according to your output directory

